name = "trust"
version = "0.0.1"

description = "Data validation library for Gleam"
licences = ["MIT"]
repository = { type = "github", user = "krystofrezac", repo = "trust" }

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
