name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "1.0.0"
          rebar3-version: "3"
      - uses: actions/setup-node@v3.5.1
        with:
          node-version: "20.12.1"
      - run: gleam deps download
      - run: gleam test
      - run: gleam test --target erlang
      - run: gleam test --target javascript
      - run: gleam format --check src test
